# Generated by Django 5.0 on 2024-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('genr', models.CharField(max_length=56)),
                ('publicdate', models.DateField()),
                ('teatr', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=500)),
                ('image_poster', models.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=50)),
                ('teatr', models.CharField(max_length=78)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('trilevideo', models.FileField(blank=True, upload_to='static/video')),
            ],
        ),
        migrations.CreateModel(
            name='Teatr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('teatraddres', models.CharField(max_length=77)),
            ],
        ),
        migrations.CreateModel(
            name='Ticketorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeshow', models.DateField()),
                ('name_kilent', models.CharField(max_length=88)),
                ('number_kilent', models.CharField(max_length=199)),
                ('ticket_summa', models.CharField(max_length=1000000)),
                ('data_payment', models.DateTimeField(null=0)),
            ],
        ),
    ]
